### ISSUE TITLE
Entity Mover trigger duration property not respected (invalid field)

### ISSUE THREAD

**Issue by MikosDrafle** [JaThePlayer/FrostHelper#5]
As shown in this screenshot, the trigger duration is improperly input in the class file, which causes the entity to default to 1 second.
![image](https://github.com/JaThePlayer/FrostHelper/assets/60538588/3bd201e4-ea04-44e2-9c44-acdc414d8c3d)
This can be fixed by changing one of the lines to properly respect the property.

**Comment by JaThePlayer** [comment]
Fixed in 1.50.7, thanks for the detailed bug report!
